Starsign.create(name:"Capricorn", genre_id: 1, symbol: "♑", content: "You're grumpy, so you should love this")
Starsign.create(name:"Aries",genre_id: 2,symbol: "♈", content: "You're grumpy, so you should love this")
Starsign.create(name:"Gemini", genre_id:3, symbol: "♊", content: "You're grumpy, so you should love this")
Starsign.create(name:"Cancer",genre_id:4, symbol: "♋", content: "You're grumpy, so you should love this")
Starsign.create(name:"Leo", genre_id:5, symbol: "♌", content: "You're grumpy, so you should love this")
Starsign.create(name:"Virgo", genre_id:6, symbol: "♍", content: "You're grumpy, so you should love this")
Starsign.create(name:"Libra",  genre_id:7, symbol: "♎", content: "You're grumpy, so you should love this")
Starsign.create(name:"Scorpio",  genre_id:7, symbol: "♏", content: "You're grumpy, so you should love this")
Starsign.create(name:"Sagittarius", genre_id:9, symbol: "♐", content: "You're grumpy, so you should love this")
Starsign.create(name:"Aquarius",genre_id:10, symbol: "♒", content: "You're grumpy, so you should love this")
Starsign.create(name:"Pisces",  genre_id:11, symbol: "♓", content: "You're grumpy, so you should love this")
Starsign.create(name:"Taurus",genre_id:12, symbol: "♉", content: "You're grumpy, so you should love this")

Genre.create(name: "honky-tonk")
Genre.create(name: "rock")
Genre.create(name:"blues")
Genre.create(name:"heavy-metal",)
Genre.create(name:"classical")
Genre.create(name:"r-n-b")
Genre.create(name:"jazz")
Genre.create(name:"world-music")
Genre.create(name:"edm")
Genre.create(name:"indie-pop")
Genre.create(name:"reggae")
Genre.create(name:"dance")


